language: node_js
node_js:
  - 10.15.2
deploy:
  provider: heroku
  api_key:
    secure: 2VeQMKJAIDDb2rIt65NGdBJnOdTKL3VEsS+WoZKXdaMvSo2hae3+TcNs63IT5Q84EimNDxs6rJcSJd0TU11D8DeFhaYzQ6MIic8FawEL4q9AsVUsbfYC2I2rdub1FRFb4QyqHBE7dXSDz9Ea9PmgdNdi0N5hZVM0fGfsGWg0VzX7xlghGWhnL0gqGrGZb6qZhKgg54u7eI+Ji06AstCMPXyW7JBOeUDb64VTh2elixfJ20+6Dc0SATExFdZzLbLoJ6AV1eimZj/1Y9SSaVgrhgu4N8we1WEoxArX649BPFmEXBHPnTXBOkTzxlASFER4UyPNryvnaiGTS8rj4hX7jr73JB+AYqDhQpi5YTaZNc+S1DKuijNOjpADFQMrwJKE5OjjsKv4LQdzRG4H711wJnV+/wc/8QRJhhT7eeFrJCfhuZJgY9NCerVAWpfTMtgRbuZwxCTVivGd/eqDy1LImW7Aozo8SxDjetJD3Q8h91iWjPyRcS1/Dn0+HKBSxP1efM+H6A6UICZouwHq4t0/NzMkga09o4j0KqSrjLkgyzgK58J/UdNj1bwXNq6lxhlshydVynk11XdZ1UwoXot1v5hWZELsrtA9ceNYecf8Pwsy81Wz2+nacRu1DoFxHvhKP+giuTx8cGB7hD3/aciM6IZqIOJF1t25BeaIQAqlKN4=
